export const REALTIME_AUTH_SERVICE = Symbol('REALTIME_AUTH_SERVICE');
export const REALTIME_ROOM_ACCESS_SERVICE = Symbol('REALTIME_ROOM_ACCESS_SERVICE');
export const REALTIME_DISCONNECT_SERVICE = Symbol('REALTIME_DISCONNECT_SERVICE');
export const REALTIME_TURN_EDIT_SERVICE = Symbol('REALTIME_TURN_EDIT_SERVICE');
export const REALTIME_SUPPORT_STATE_STORE = Symbol('REALTIME_SUPPORT_STATE_STORE');
export const REALTIME_TURN_SUBMIT_SERVICE = Symbol('REALTIME_TURN_SUBMIT_SERVICE');
export const REALTIME_ASSISTIVE_MESSAGE_SERVICE = Symbol('REALTIME_ASSISTIVE_MESSAGE_SERVICE');

export const REALTIME_EVENT = {
  JOIN_ROOM: 'join-room',
  ROOM_PARTICIPANTS_UPDATED: 'room-participants-updated',
  GAME_STARTED: 'game-started',
  CODE_CHANGE: 'code-change',
  CODE_UPDATED: 'code-updated',
  TURN_SUBMIT: 'turn-submit',
  TURN_EVALUATED: 'turn-evaluated',
  TURN_CHANGED: 'turn-changed',
  GAME_STATE_UPDATED: 'game-state-updated',
  MISSION_RESULT: 'mission-result',
} as const;

export const REALTIME_CLOSE_CODE = {
  AUTH_TOKEN_INVALID: 4401,
  FORBIDDEN_RESOURCE_ACCESS: 4403,
  GAME_ROOM_NOT_FOUND: 4404,
  NORMAL_CLOSURE: 1000,
} as const;

export const REALTIME_CLOSE_REASON = {
  AUTH_TOKEN_INVALID: 'AUTH_TOKEN_INVALID',
  FORBIDDEN_RESOURCE_ACCESS: 'FORBIDDEN_RESOURCE_ACCESS',
  GAME_ROOM_NOT_FOUND: 'GAME_ROOM_NOT_FOUND',
} as const;
